name: ticket_scanner
description: "Ticket Scanner App for Lovro"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  simple_barcode_scanner: ^0.1.1
  permission_handler : 11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.9.2"
  


flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  image: assets/images/splash.png
  color: "42a5f5"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/lovro.png"